//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright ...

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package videoDTO

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoCreateDTO) DeepCopyInto(out *VideoCreateDTO) {
	*out = *in
	if in.Actors != nil {
		in, out := &in.Actors, &out.Actors
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoCreateDTO.
func (in *VideoCreateDTO) DeepCopy() *VideoCreateDTO {
	if in == nil {
		return nil
	}
	out := new(VideoCreateDTO)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoItemDTO) DeepCopyInto(out *VideoItemDTO) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoItemDTO.
func (in *VideoItemDTO) DeepCopy() *VideoItemDTO {
	if in == nil {
		return nil
	}
	out := new(VideoItemDTO)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoPageDTO) DeepCopyInto(out *VideoPageDTO) {
	*out = *in
	if in.Actors != nil {
		in, out := &in.Actors, &out.Actors
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoPageDTO.
func (in *VideoPageDTO) DeepCopy() *VideoPageDTO {
	if in == nil {
		return nil
	}
	out := new(VideoPageDTO)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoSearchDTO) DeepCopyInto(out *VideoSearchDTO) {
	*out = *in
	if in.Actors != nil {
		in, out := &in.Actors, &out.Actors
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoSearchDTO.
func (in *VideoSearchDTO) DeepCopy() *VideoSearchDTO {
	if in == nil {
		return nil
	}
	out := new(VideoSearchDTO)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoUpdateDTO) DeepCopyInto(out *VideoUpdateDTO) {
	*out = *in
	if in.ActorIds != nil {
		in, out := &in.ActorIds, &out.ActorIds
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoUpdateDTO.
func (in *VideoUpdateDTO) DeepCopy() *VideoUpdateDTO {
	if in == nil {
		return nil
	}
	out := new(VideoUpdateDTO)
	in.DeepCopyInto(out)
	return out
}
