//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright ...

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package actorDO

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActorDO) DeepCopyInto(out *ActorDO) {
	*out = *in
	in.Details.DeepCopyInto(&out.Details)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActorDO.
func (in *ActorDO) DeepCopy() *ActorDO {
	if in == nil {
		return nil
	}
	out := new(ActorDO)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActorDetailsDO) DeepCopyInto(out *ActorDetailsDO) {
	*out = *in
	if in.VideoIds != nil {
		in, out := &in.VideoIds, &out.VideoIds
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
	if in.GalleryIds != nil {
		in, out := &in.GalleryIds, &out.GalleryIds
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActorDetailsDO.
func (in *ActorDetailsDO) DeepCopy() *ActorDetailsDO {
	if in == nil {
		return nil
	}
	out := new(ActorDetailsDO)
	in.DeepCopyInto(out)
	return out
}
