//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright ...

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package galleryDTO

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GalleryCreateDTO) DeepCopyInto(out *GalleryCreateDTO) {
	*out = *in
	if in.Actors != nil {
		in, out := &in.Actors, &out.Actors
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GalleryCreateDTO.
func (in *GalleryCreateDTO) DeepCopy() *GalleryCreateDTO {
	if in == nil {
		return nil
	}
	out := new(GalleryCreateDTO)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GalleryItemDTO) DeepCopyInto(out *GalleryItemDTO) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GalleryItemDTO.
func (in *GalleryItemDTO) DeepCopy() *GalleryItemDTO {
	if in == nil {
		return nil
	}
	out := new(GalleryItemDTO)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GalleryPageDTO) DeepCopyInto(out *GalleryPageDTO) {
	*out = *in
	if in.Actors != nil {
		in, out := &in.Actors, &out.Actors
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GalleryPageDTO.
func (in *GalleryPageDTO) DeepCopy() *GalleryPageDTO {
	if in == nil {
		return nil
	}
	out := new(GalleryPageDTO)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GallerySearchDTO) DeepCopyInto(out *GallerySearchDTO) {
	*out = *in
	if in.Actors != nil {
		in, out := &in.Actors, &out.Actors
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GallerySearchDTO.
func (in *GallerySearchDTO) DeepCopy() *GallerySearchDTO {
	if in == nil {
		return nil
	}
	out := new(GallerySearchDTO)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GalleryUpdateDTO) DeepCopyInto(out *GalleryUpdateDTO) {
	*out = *in
	if in.Actors != nil {
		in, out := &in.Actors, &out.Actors
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GalleryUpdateDTO.
func (in *GalleryUpdateDTO) DeepCopy() *GalleryUpdateDTO {
	if in == nil {
		return nil
	}
	out := new(GalleryUpdateDTO)
	in.DeepCopyInto(out)
	return out
}
