//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright ...

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package actorDTO

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActorArtDTO) DeepCopyInto(out *ActorArtDTO) {
	*out = *in
	if in.VideoIds != nil {
		in, out := &in.VideoIds, &out.VideoIds
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
	if in.GalleryIds != nil {
		in, out := &in.GalleryIds, &out.GalleryIds
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActorArtDTO.
func (in *ActorArtDTO) DeepCopy() *ActorArtDTO {
	if in == nil {
		return nil
	}
	out := new(ActorArtDTO)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActorCreateDTO) DeepCopyInto(out *ActorCreateDTO) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActorCreateDTO.
func (in *ActorCreateDTO) DeepCopy() *ActorCreateDTO {
	if in == nil {
		return nil
	}
	out := new(ActorCreateDTO)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActorItemDTO) DeepCopyInto(out *ActorItemDTO) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActorItemDTO.
func (in *ActorItemDTO) DeepCopy() *ActorItemDTO {
	if in == nil {
		return nil
	}
	out := new(ActorItemDTO)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActorPageDTO) DeepCopyInto(out *ActorPageDTO) {
	*out = *in
	in.Art.DeepCopyInto(&out.Art)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActorPageDTO.
func (in *ActorPageDTO) DeepCopy() *ActorPageDTO {
	if in == nil {
		return nil
	}
	out := new(ActorPageDTO)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActorRemoveArtDTO) DeepCopyInto(out *ActorRemoveArtDTO) {
	*out = *in
	in.Art.DeepCopyInto(&out.Art)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActorRemoveArtDTO.
func (in *ActorRemoveArtDTO) DeepCopy() *ActorRemoveArtDTO {
	if in == nil {
		return nil
	}
	out := new(ActorRemoveArtDTO)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActorSearchDTO) DeepCopyInto(out *ActorSearchDTO) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActorSearchDTO.
func (in *ActorSearchDTO) DeepCopy() *ActorSearchDTO {
	if in == nil {
		return nil
	}
	out := new(ActorSearchDTO)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActorUpdateDTO) DeepCopyInto(out *ActorUpdateDTO) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActorUpdateDTO.
func (in *ActorUpdateDTO) DeepCopy() *ActorUpdateDTO {
	if in == nil {
		return nil
	}
	out := new(ActorUpdateDTO)
	in.DeepCopyInto(out)
	return out
}
